from iac_smith.models.change_plan import ChangePlan
from iac_smith.models.intent import InfrastructureIntent, SupportedIntent
from iac_smith.models.repo_patterns import RepoPatterns


def _header() -> str:
    return "# Generated by IaC Smith. Review before apply.\n"


def _repo_slug(target_repo: str) -> str:
    return target_repo.split("/")[-1]


def _root_terragrunt(change_plan: ChangePlan, intent: InfrastructureIntent) -> str:
    first_env = change_plan.environments[0]
    backend = change_plan.backend_resources[first_env]
    return f'''{_header()}
locals {{
  aws_region = "{intent.region}"
}}

remote_state {{
  backend = "s3"
  config = {{
    bucket         = "{backend.bucket}"
    key            = "${{path_relative_to_include()}}/terraform.tfstate"
    region         = local.aws_region
    encrypt        = true
    dynamodb_table = "{backend.lock_table}"
  }}
}}
'''


def _env_terragrunt(env: str, intent: InfrastructureIntent) -> str:
    return f'''{_header()}
locals {{
  environment = "{env}"
  aws_region  = "{intent.region}"
}}
'''


def _stack_terragrunt(stack_name: str, env: str, intent: InfrastructureIntent) -> str:
    name_prefix = f"{stack_name}-{env}"
    return f'''{_header()}
include "root" {{
  path = find_in_parent_folders()
}}

include "env" {{
  path   = find_in_parent_folders("{env}/terragrunt.hcl")
  expose = true
}}

terraform {{
  source = "../../../modules/{stack_name}"
}}

inputs = {{
  name_prefix = "{name_prefix}"
  environment = "{env}"
  aws_region  = "{intent.region}"
}}
'''


def _module_readme(stack_name: str) -> str:
    return f"""# {stack_name}

Terraform module generated by IaC Smith.

<!-- BEGIN_TF_DOCS -->
<!-- END_TF_DOCS -->
"""


def _vpc_main() -> str:
    return """module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = var.name_prefix
  cidr = var.vpc_cidr

  azs             = var.availability_zones
  private_subnets = var.private_subnets
  public_subnets  = var.public_subnets

  enable_nat_gateway = true
  single_nat_gateway = true

  tags = var.tags
}
"""


def _eks_fargate_main() -> str:
    return """module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "${var.name_prefix}-vpc"
  cidr = var.vpc_cidr

  azs             = var.availability_zones
  private_subnets = var.private_subnets
  public_subnets  = var.public_subnets

  enable_nat_gateway = true
  single_nat_gateway = true

  tags = var.tags
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 20.0"

  cluster_name    = var.name_prefix
  cluster_version = var.cluster_version

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  enable_cluster_creator_admin_permissions = true

  fargate_profiles = {
    default = {
      selectors = [
        { namespace = "default" },
        { namespace = "kube-system" },
      ]
    }
  }

  tags = var.tags
}
"""


def _ecs_fargate_main() -> str:
    return """module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "${var.name_prefix}-vpc"
  cidr = var.vpc_cidr

  azs             = var.availability_zones
  private_subnets = var.private_subnets
  public_subnets  = var.public_subnets

  enable_nat_gateway = true
  single_nat_gateway = true

  tags = var.tags
}

resource "aws_ecs_cluster" "this" {
  name = var.name_prefix
  tags = var.tags
}
"""


def _rds_postgres_main() -> str:
    return """module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "${var.name_prefix}-vpc"
  cidr = var.vpc_cidr

  azs             = var.availability_zones
  private_subnets = var.private_subnets
  public_subnets  = var.public_subnets

  enable_nat_gateway = true
  single_nat_gateway = true

  tags = var.tags
}

resource "aws_security_group" "db" {
  name        = "${var.name_prefix}-db"
  description = "Private database access"
  vpc_id      = module.vpc.vpc_id

  tags = var.tags
}

module "db" {
  source  = "terraform-aws-modules/rds/aws"
  version = "~> 6.0"

  identifier = var.name_prefix

  engine               = "postgres"
  engine_version       = var.postgres_engine_version
  family               = var.postgres_parameter_group_family
  major_engine_version = var.postgres_major_engine_version
  instance_class       = var.db_instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_encrypted     = true

  db_name  = var.database_name
  username = var.database_username
  port     = 5432

  manage_master_user_password = true
  create_db_subnet_group      = true
  subnet_ids                  = module.vpc.private_subnets
  vpc_security_group_ids      = [aws_security_group.db.id]
  publicly_accessible         = false
  deletion_protection         = var.deletion_protection
  skip_final_snapshot         = var.skip_final_snapshot

  backup_retention_period = var.backup_retention_period
  multi_az                = var.multi_az

  tags = var.tags
}
"""


def _module_variables(stack_name: str) -> str:
    extra = ""
    if stack_name == "eks-fargate":
        extra = """
variable "cluster_version" {
  description = "EKS cluster version."
  type        = string
  default     = "1.30"
}
"""
    if stack_name == "rds-postgres":
        extra = """
variable "postgres_engine_version" {
  description = "PostgreSQL engine version."
  type        = string
  default     = "16.3"
}

variable "postgres_parameter_group_family" {
  description = "PostgreSQL parameter group family."
  type        = string
  default     = "postgres16"
}

variable "postgres_major_engine_version" {
  description = "PostgreSQL major engine version."
  type        = string
  default     = "16"
}

variable "db_instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  description = "Initial allocated storage in GiB."
  type        = number
  default     = 20
}

variable "max_allocated_storage" {
  description = "Maximum autoscaled storage in GiB."
  type        = number
  default     = 100
}

variable "database_name" {
  description = "Initial database name."
  type        = string
  default     = "app"
}

variable "database_username" {
  description = "Master database username. Password is AWS-managed."
  type        = string
  default     = "appadmin"
}

variable "deletion_protection" {
  description = "Whether deletion protection is enabled."
  type        = bool
  default     = true
}

variable "skip_final_snapshot" {
  description = "Whether to skip final snapshot on deletion."
  type        = bool
  default     = false
}

variable "backup_retention_period" {
  description = "Backup retention period in days."
  type        = number
  default     = 7
}

variable "multi_az" {
  description = "Whether to run a Multi-AZ RDS deployment."
  type        = bool
  default     = false
}
"""
    return f"""variable "name_prefix" {{
  description = "Name prefix for generated resources."
  type        = string
}}

variable "environment" {{
  description = "Deployment environment."
  type        = string
}}

variable "aws_region" {{
  description = "AWS region."
  type        = string
}}

variable "vpc_cidr" {{
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.0.0.0/16"
}}

variable "availability_zones" {{
  description = "Availability zones for subnet placement."
  type        = list(string)
  default     = []
}}

variable "private_subnets" {{
  description = "Private subnet CIDR blocks."
  type        = list(string)
  default     = ["10.0.1.0/24", "10.0.2.0/24"]
}}

variable "public_subnets" {{
  description = "Public subnet CIDR blocks."
  type        = list(string)
  default     = ["10.0.101.0/24", "10.0.102.0/24"]
}}

variable "tags" {{
  description = "Tags applied to generated resources."
  type        = map(string)
  default     = {{}}
}}
{extra}"""


def _module_outputs(stack_name: str) -> str:
    if stack_name == "vpc":
        return """output "vpc_id" {
  description = "Created VPC ID."
  value       = module.vpc.vpc_id
}

output "private_subnets" {
  description = "Created private subnet IDs."
  value       = module.vpc.private_subnets
}
"""
    if stack_name == "eks-fargate":
        return """output "cluster_name" {
  description = "EKS cluster name."
  value       = module.eks.cluster_name
}

output "vpc_id" {
  description = "Created VPC ID."
  value       = module.vpc.vpc_id
}
"""
    if stack_name == "rds-postgres":
        return """output "db_instance_endpoint" {
  description = "RDS instance endpoint."
  value       = module.db.db_instance_endpoint
}

output "db_instance_arn" {
  description = "RDS instance ARN."
  value       = module.db.db_instance_arn
}

output "vpc_id" {
  description = "Created VPC ID."
  value       = module.vpc.vpc_id
}
"""
    return """output "cluster_name" {
  description = "ECS cluster name."
  value       = aws_ecs_cluster.this.name
}

output "vpc_id" {
  description = "Created VPC ID."
  value       = module.vpc.vpc_id
}
"""


def _versions() -> str:
    return """terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}
"""


def _backend_bootstrap(env: str, change_plan: ChangePlan, intent: InfrastructureIntent) -> str:
    backend = change_plan.backend_resources[env]
    return f'''terraform {{
  required_version = ">= 1.6.0"

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "{intent.region}"
}}

resource "aws_s3_bucket" "tfstate" {{
  bucket = "{backend.bucket}"
}}

resource "aws_s3_bucket_versioning" "tfstate" {{
  bucket = aws_s3_bucket.tfstate.id
  versioning_configuration {{
    status = "Enabled"
  }}
}}

resource "aws_s3_bucket_server_side_encryption_configuration" "tfstate" {{
  bucket = aws_s3_bucket.tfstate.id

  rule {{
    apply_server_side_encryption_by_default {{
      sse_algorithm = "AES256"
    }}
  }}
}}

resource "aws_s3_bucket_public_access_block" "tfstate" {{
  bucket = aws_s3_bucket.tfstate.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}}

resource "aws_dynamodb_table" "tflock" {{
  name         = "{backend.lock_table}"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"

  attribute {{
    name = "LockID"
    type = "S"
  }}
}}
'''


def _workflow_check() -> str:
    return """name: Terraform PR Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
      - name: Terraform format check
        run: terraform fmt -check -recursive
"""


def _workflow_apply() -> str:
    return """name: Terraform Apply

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Apply placeholder
        run: echo "Configure repository-specific apply workflow before enabling automatic applies."
"""


def _module_main(stack_name: str) -> str:
    if stack_name == "vpc":
        return _vpc_main()
    if stack_name == "eks-fargate":
        return _eks_fargate_main()
    if stack_name == "ecs-fargate":
        return _ecs_fargate_main()
    if stack_name == "rds-postgres":
        return _rds_postgres_main()
    raise ValueError(f"No module renderer for {stack_name}")


def generate_files(
    intent: InfrastructureIntent,
    change_plan: ChangePlan,
    repo_patterns: RepoPatterns,
    target_repo: str,
) -> dict[str, str]:
    del repo_patterns  # The current renderer follows detected layout through ChangePlan paths.
    files: dict[str, str] = {}
    files["README.md"] = (
        f"# {_repo_slug(target_repo)}\n\nInfrastructure managed through Terraform/Terragrunt.\n"
    )
    files["live/terragrunt.hcl"] = _root_terragrunt(change_plan, intent)
    files[".github/workflows/terraform-pr-check.yml"] = _workflow_check()
    files[".github/workflows/terraform-apply.yml"] = _workflow_apply()

    for env in change_plan.environments:
        files[f"live/{env}/terragrunt.hcl"] = _env_terragrunt(env, intent)
        files[f"bootstrap/backend/{env}/main.tf"] = _backend_bootstrap(env, change_plan, intent)
        files[f"bootstrap/backend/{env}/variables.tf"] = ""
        files[f"bootstrap/backend/{env}/outputs.tf"] = ""
        files[f"bootstrap/backend/{env}/README.md"] = f"# {env} backend bootstrap\n"
        if intent.supported_intent != SupportedIntent.BASELINE:
            files[f"live/{env}/{change_plan.stack_name}/terragrunt.hcl"] = _stack_terragrunt(
                change_plan.stack_name, env, intent
            )
            files[f"live/{env}/{change_plan.stack_name}/README.md"] = (
                f"# {env} {change_plan.stack_name}\n"
            )

    if intent.supported_intent != SupportedIntent.BASELINE:
        stack = change_plan.stack_name
        files[f"modules/{stack}/main.tf"] = _module_main(stack)
        files[f"modules/{stack}/variables.tf"] = _module_variables(stack)
        files[f"modules/{stack}/outputs.tf"] = _module_outputs(stack)
        files[f"modules/{stack}/versions.tf"] = _versions()
        files[f"modules/{stack}/README.md"] = _module_readme(stack)

    return {
        path: content for path, content in files.items() if path in change_plan.files_to_generate
    }
