import re

from iac_smith.models.change_plan import ChangePlan
from iac_smith.models.intent import InfrastructureIntent
from iac_smith.models.validation import ValidationResult


def branch_name_for_issue(issue_number: int, issue_title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", issue_title.lower()).strip("-")[:48]
    return f"iac-smith/issue-{issue_number}-{slug}"


def _bullets(items: list[str]) -> str:
    if not items:
        return "None."
    return "\n".join(f"* {item}" for item in items)


def _checks(items: list[str]) -> str:
    if not items:
        return "None."
    return "\n".join(f"- ✅ {item}" for item in items)


def _structure_only_warnings(generated_files: dict[str, str] | None) -> list[str]:
    if not generated_files:
        return []
    module_main_files = {
        path: content
        for path, content in generated_files.items()
        if path.startswith("modules/") and path.endswith("/main.tf")
    }
    if module_main_files and all(
        "No provider resources were selected" in content for content in module_main_files.values()
    ):
        return [
            "Structure-only PR: the spec renderer selected no provider resources, "
            "so generated module bodies are placeholders until generic "
            "registry/module or provider-schema composition is implemented."
        ]
    return []


def build_pr_body(
    issue_url: str,
    intent: InfrastructureIntent,
    change_plan: ChangePlan,
    validation: ValidationResult,
    runtime_checks: list[str] | None = None,
    generated_files: dict[str, str] | None = None,
) -> str:
    changed_files = "\n".join(f"* `{path}`" for path in change_plan.files_to_generate)
    backend_lines = "\n".join(
        f"* `{env}`: S3 `{resource.bucket}`, DynamoDB `{resource.lock_table}`"
        for env, resource in change_plan.backend_resources.items()
    )
    validation_block = f"**Security review**\n\n{_checks(validation.checks)}"
    if runtime_checks:
        validation_block += (
            "\n\n**Terraform / Terragrunt validation**\n\n"
            "IaC Smith ran these commands locally before opening this PR:\n\n"
            f"{_checks(runtime_checks)}"
        )
    warnings = [
        *intent.warnings,
        *validation.warnings,
        *validation.structural,
        *_structure_only_warnings(generated_files),
    ]
    return f"""## Source issue

{issue_url}

## Generated infrastructure summary

{_bullets(change_plan.summary)}

Target environments: {", ".join(change_plan.environments)}
Region: `{intent.region}`
Stack: `{change_plan.stack_name}`

## Assumptions and defaults

{_bullets(intent.assumptions)}

## Files created or changed

{changed_files}

## Backend resources

{backend_lines}

## Validation results

{validation_block}

## Warnings and risks

{_bullets(warnings)}

## Iterating on this infrastructure

To add to or modify this infrastructure, create a new GitHub issue in the controller repository
labeled `iac-smith` describing the change. IaC Smith reads existing files in the target repo
before generating anything — follow-on PRs build on what was already merged.

## Before you apply

This infrastructure was generated by an LLM. Review every file in this PR — the
Terraform/Terragrunt source, the workflows, and the backend configuration — before merging.
IaC Smith did not apply anything; nothing reaches AWS until you merge and approve the
apply workflow's environment gate.
"""
