from iac_smith.graph import build_graph, default_file_generator
from iac_smith.models.change_plan import BackendResource, ChangePlan
from iac_smith.models.intent import EnvironmentScope, InfrastructureIntent
from iac_smith.models.repo_patterns import RepoPatterns
from iac_smith.models.rules import Ruleset
from iac_smith.state import IaCSmithState


def _fake_intent_parser(issue_text: str) -> InfrastructureIntent:
    if "apply" in issue_text.lower():
        return InfrastructureIntent(
            raw_request=issue_text,
            resource_type="",
            environment_scope=EnvironmentScope.PROD_ONLY,
            environments=["prod"],
            region="us-west-2",
            blocked=True,
            block_reason="Issue requests terraform apply directly.",
        )
    return InfrastructureIntent(
        raw_request=issue_text,
        resource_type="eks_fargate",
        environment_scope=EnvironmentScope.NON_PROD_ONLY,
        environments=["non-prod"],
        region="us-west-2",
        requires_new_vpc=True,
        features=["remote_state", "private_subnets"],
        assumptions=["Created a new VPC because no existing network was specified."],
    )


def _fake_graph_file_generator(*, intent, change_plan, repo_patterns, ruleset, target_repo, repo_path=None):
    return {"modules/eks-fargate/main.tf": 'resource "aws_ecs_cluster" "this" { name = "test" }\n'}


def _graph():
    return build_graph(
        intent_parser_fn=_fake_intent_parser,
        file_generator_fn=_fake_graph_file_generator,
    )


def test_default_file_generator_uses_bedrock_dynamic_generator(monkeypatch):
    calls = []

    class FakeBedrockTerraformGenerator:
        def generate_files(self, **kwargs):
            calls.append(kwargs)
            return {"modules/example/main.tf": "# generated by model\n"}

    monkeypatch.setattr(
        "iac_smith.graph.BedrockTerraformGenerator",
        FakeBedrockTerraformGenerator,
    )
    intent = InfrastructureIntent(
        raw_request="Create example infrastructure",
        resource_type="example",
        environment_scope=EnvironmentScope.NON_PROD_ONLY,
        environments=["non-prod"],
        region="us-west-2",
    )
    change_plan = ChangePlan(
        stack_name="example",
        environments=["non-prod"],
        files_to_generate=["modules/example/main.tf"],
        backend_resources={"non-prod": BackendResource(bucket="state", lock_table="lock")},
        summary=["Generate example infrastructure"],
    )
    ruleset = Ruleset(rules=[])

    files = default_file_generator(
        intent=intent,
        change_plan=change_plan,
        repo_patterns=RepoPatterns(),
        ruleset=ruleset,
        target_repo="time4116/iac-smith-demo-infra",
    )

    assert files == {"modules/example/main.tf": "# generated by model\n"}
    assert calls[0]["ruleset"] is ruleset
    assert calls[0]["change_plan"] is change_plan


def test_graph_passes_ruleset_and_repo_context_to_injected_file_generator(tmp_path):
    calls = []

    def fake_file_generator(*, intent, change_plan, repo_patterns, ruleset, target_repo, repo_path=None):
        calls.append(
            {
                "intent": intent,
                "change_plan": change_plan,
                "repo_patterns": repo_patterns,
                "ruleset": ruleset,
                "target_repo": target_repo,
            }
        )
        return {
            "modules/eks-fargate/main.tf": 'resource "aws_ecs_cluster" "this" { name = "test" }\n'
        }

    (tmp_path / "rules").mkdir()
    (tmp_path / "rules" / "terraform.yaml").write_text(
        "rules:\n"
        "  - id: dynamic-generation-rule\n"
        "    severity: warning\n"
        "    description: Follow dynamic generation rules.\n",
        encoding="utf-8",
    )
    (tmp_path / "environments" / "non-prod").mkdir(parents=True)
    (tmp_path / "environments" / "non-prod" / "terragrunt.hcl").write_text("locals {}\n")

    graph = build_graph(
        intent_parser_fn=_fake_intent_parser,
        file_generator_fn=fake_file_generator,
    )
    result = graph.invoke(
        IaCSmithState(
            issue_number=12,
            issue_title="Create EKS Fargate infra",
            issue_body="Create AWS infrastructure for a non-prod EKS Fargate setup in us-west-2.",
            issue_url="https://github.com/time4116/iac-smith/issues/12",
            labels=["iac-smith"],
            target_repo="time4116/iac-smith-demo-infra",
            target_repo_path=str(tmp_path),
        )
    )

    assert result["status"] == "pr_ready"
    assert calls[0]["target_repo"] == "time4116/iac-smith-demo-infra"
    assert calls[0]["repo_patterns"].uses_terragrunt is True
    assert isinstance(calls[0]["ruleset"], Ruleset)
    assert calls[0]["ruleset"].rules[0].id == "dynamic-generation-rule"


def test_graph_passes_repo_path_to_file_generator(tmp_path):
    received_repo_path = []

    def fake_file_generator(*, intent, change_plan, repo_patterns, ruleset, target_repo, repo_path=None):
        received_repo_path.append(repo_path)
        return {"modules/eks-fargate/main.tf": 'resource "aws_ecs_cluster" "this" { name = "test" }\n'}

    graph = build_graph(
        intent_parser_fn=_fake_intent_parser,
        file_generator_fn=fake_file_generator,
    )
    graph.invoke(
        IaCSmithState(
            issue_number=12,
            issue_title="Create EKS Fargate infra",
            issue_body="Create AWS infrastructure for a non-prod EKS Fargate setup in us-west-2.",
            issue_url="https://github.com/time4116/iac-smith/issues/12",
            labels=["iac-smith"],
            target_repo="time4116/iac-smith-demo-infra",
            target_repo_path=str(tmp_path),
        )
    )

    from pathlib import Path

    assert received_repo_path[0] == Path(tmp_path)


def test_graph_compiles_and_routes_supported_issue_to_generated_pr_ready(tmp_path):
    graph = _graph()
    result = graph.invoke(
        IaCSmithState(
            issue_number=12,
            issue_title="Create EKS Fargate infra",
            issue_body="Create AWS infrastructure for a non-prod EKS Fargate setup in us-west-2.",
            issue_url="https://github.com/time4116/iac-smith/issues/12",
            labels=["iac-smith"],
            target_repo="time4116/iac-smith-demo-infra",
            target_repo_path=str(tmp_path),
        )
    )

    assert result["status"] == "pr_ready"
    assert result["intent"].resource_type == "eks_fargate"
    assert result["change_plan"].stack_name == "eks-fargate"
    assert result["validation"].status.value in {"passed", "partial"}
    assert "modules/eks-fargate/main.tf" in result["generated_files"]
    assert result["pr_body"] is not None


def test_graph_blocks_apply_request_before_pr_writer():
    graph = _graph()
    result = graph.invoke(
        IaCSmithState(
            issue_number=13,
            issue_title="Apply terraform",
            issue_body="Please apply terraform now.",
            issue_url="https://github.com/time4116/iac-smith/issues/13",
            labels=["iac-smith"],
            target_repo="time4116/iac-smith-demo-infra",
        )
    )

    assert result["status"] == "blocked"
    assert result.get("pr_body") is None
    assert result["intent"].blocked is True


def test_graph_ignores_unlabeled_issue_before_intent_parsing():
    graph = _graph()
    result = graph.invoke(
        IaCSmithState(
            issue_number=14,
            issue_title="Create EKS Fargate infra",
            issue_body="Create AWS infrastructure for a non-prod EKS Fargate setup in us-west-2.",
            issue_url="https://github.com/time4116/iac-smith/issues/14",
            labels=[],
            target_repo="time4116/iac-smith-demo-infra",
        )
    )

    assert result["status"] == "ignored"
    assert result["block_reason"] == "Missing iac-smith label"
    assert "intent" not in result
    assert "change_plan" not in result
    assert "pr_body" not in result


def test_graph_blocks_failed_static_review_before_pr_writer():
    # To test that persistent failures get blocked after reaching the max retry threshold,
    # we inject a fake file generator that always returns a failing Terragrunt file.
    def broken_generator(*args, **kwargs):
        return {
            "environments/non-prod/example/terragrunt.hcl": (
                'remote_state { config = { key = "fixed.tfstate" } }'
            )
        }

    graph = build_graph(
        intent_parser_fn=_fake_intent_parser,
        file_generator_fn=broken_generator,
    )
    result = graph.invoke(
        IaCSmithState(
            issue_number=15,
            issue_title="Create EKS Fargate infra",
            issue_body="Create AWS infrastructure for a non-prod EKS Fargate setup in us-west-2.",
            issue_url="https://github.com/time4116/iac-smith/issues/15",
            labels=["iac-smith"],
            target_repo="time4116/iac-smith-demo-infra",
            generated_files={
                "environments/non-prod/example/terragrunt.hcl": (
                    'remote_state { config = { key = "fixed.tfstate" } }'
                )
            },
        )
    )

    assert result["status"] == "blocked"
    assert "pr_body" not in result
    assert result["validation"].status.value == "failed"
    assert result["repair_attempts"] == 3


def test_graph_validation_runner_successfully_repairs_transient_failure():
    attempts_called = 0

    def recovering_generator(*args, **kwargs):
        nonlocal attempts_called
        attempts_called += 1
        if attempts_called == 1:
            # First attempt: returns a failed/broken state key
            return {
                "environments/non-prod/example/terragrunt.hcl": (
                    'remote_state { config = { key = "fixed.tfstate" } }'
                )
            }
        # Second attempt: returns healed/repaired state key
        repaired_key = (
            'remote_state { config = { key = "${path_relative_to_include()}/terraform.tfstate" } }'
        )
        return {"environments/non-prod/example/terragrunt.hcl": repaired_key}

    graph = build_graph(
        intent_parser_fn=_fake_intent_parser,
        file_generator_fn=recovering_generator,
    )

    result = graph.invoke(
        IaCSmithState(
            issue_number=16,
            issue_title="Create EKS Fargate infra",
            issue_body="Create AWS infrastructure for a non-prod EKS Fargate setup in us-west-2.",
            issue_url="https://github.com/time4116/iac-smith/issues/16",
            labels=["iac-smith"],
            target_repo="time4116/iac-smith-demo-infra",
        )
    )

    assert result["status"] == "pr_ready"
    assert result["validation"].status.value == "passed"
    assert result["repair_attempts"] == 1
    assert attempts_called == 2
