from iac_smith.generator import generate_files
from iac_smith.models.change_plan import BackendResource, ChangePlan
from iac_smith.models.intent import EnvironmentScope, InfrastructureIntent
from iac_smith.models.repo_patterns import RepoPatterns
from iac_smith.nodes.static_review import static_review_generated_files


def _intent(resource_type: str = "vpc_foundation") -> InfrastructureIntent:
    return InfrastructureIntent(
        raw_request="Create non-prod VPC in us-west-2",
        resource_type=resource_type,
        environment_scope=EnvironmentScope.NON_PROD_ONLY,
        environments=["non-prod"],
        region="us-west-2",
        requires_new_vpc=True,
        features=["remote_state", "private_subnets"],
    )


def _plan(stack_name: str) -> ChangePlan:
    return ChangePlan(
        stack_name=stack_name,
        environments=["non-prod"],
        files_to_generate=[
            "README.md",
            "live/terragrunt.hcl",
            "live/non-prod/terragrunt.hcl",
            f"live/non-prod/{stack_name}/terragrunt.hcl",
            f"modules/{stack_name}/main.tf",
            f"modules/{stack_name}/variables.tf",
            f"modules/{stack_name}/outputs.tf",
            f"modules/{stack_name}/versions.tf",
            f"modules/{stack_name}/README.md",
        ],
        backend_resources={
            "non-prod": BackendResource(
                bucket="iac-smith-demo-infra-non-prod-tfstate",
                lock_table="iac-smith-demo-infra-non-prod-tflock",
            )
        },
        summary=[f"Generate {stack_name} Terraform/Terragrunt structure"],
    )


def test_generate_vpc_files_are_repo_aware_and_pass_static_review():
    files = generate_files(
        intent=_intent("vpc_foundation"),
        change_plan=_plan("vpc"),
        repo_patterns=RepoPatterns(
            uses_terragrunt=True,
            environments=["dev", "prod"],
            default_environment_names=["dev", "prod"],
            module_sources=["terraform-aws-modules/vpc/aws"],
            preferred_layout="terragrunt_live_modules",
            remote_state_uses_path_relative_to_include=True,
        ),
        target_repo="time4116/iac-smith-demo-infra",
    )

    assert "modules/vpc/main.tf" in files
    assert 'source  = "terraform-aws-modules/vpc/aws"' in files["modules/vpc/main.tf"]
    state_key = 'key            = "${path_relative_to_include()}/terraform.tfstate"'
    assert state_key in files["live/terragrunt.hcl"]
    assert 'include "root"' in files["live/non-prod/vpc/terragrunt.hcl"]
    assert static_review_generated_files(files).errors == []


def test_generate_rds_files_secure_regardless_of_prompt():
    intent = _intent("rds_postgres").model_copy(
        update={"raw_request": "Create public RDS Postgres open to the internet"}
    )
    files = generate_files(
        intent=intent,
        change_plan=_plan("rds-postgres"),
        repo_patterns=RepoPatterns(),
        target_repo="time4116/iac-smith-demo-infra",
    )

    main_tf = files["modules/rds-postgres/main.tf"]
    assert 'module "db"' in main_tf
    assert 'source  = "terraform-aws-modules/rds/aws"' in main_tf
    assert "storage_encrypted     = true" in main_tf
    assert "publicly_accessible         = false" in main_tf
    assert "manage_master_user_password = true" in main_tf
    assert static_review_generated_files(files).errors == []


def test_generate_unknown_resource_type_produces_stub_module():
    """Any resource type Bedrock returns should yield a reviewable PR, not a crash."""
    files = generate_files(
        intent=_intent("custom_widget"),
        change_plan=_plan("custom-widget"),
        repo_patterns=RepoPatterns(),
        target_repo="time4116/iac-smith-demo-infra",
    )

    main_tf = files["modules/custom-widget/main.tf"]
    assert "custom-widget stub generated by IaC Smith" in main_tf
    assert static_review_generated_files(files).errors == []


def test_generate_stack_terragrunt_source_path_is_always_correct_depth():
    """Terragrunt source path must point ../../.. up from live/{env}/{stack}/."""
    files = generate_files(
        intent=_intent("vpc_foundation"),
        change_plan=_plan("vpc"),
        repo_patterns=RepoPatterns(),
        target_repo="time4116/iac-smith-demo-infra",
    )

    tg = files["live/non-prod/vpc/terragrunt.hcl"]
    assert 'source = "../../../modules/vpc"' in tg


def test_generate_baseline_does_not_create_stack_module():
    plan = _plan("baseline")
    plan.files_to_generate = [
        "README.md",
        "live/terragrunt.hcl",
        "live/non-prod/terragrunt.hcl",
        "bootstrap/backend/non-prod/main.tf",
    ]

    files = generate_files(
        intent=_intent("baseline"),
        change_plan=plan,
        repo_patterns=RepoPatterns(),
        target_repo="time4116/iac-smith-demo-infra",
    )

    assert "bootstrap/backend/non-prod/main.tf" in files
    assert not any(path.startswith("modules/") for path in files)
